### ISSUE TITLE
Passed the custom array image

### ISSUE THREAD

**Issue by vickygaugau** [Mindinventory/image-collage-widget#14]
Hi everyone,
I am using this library, it is so pretty and useful for me.
Now i dont know how to passed the my custom array image to this library
(means without the select image from "plus" button
Hope everyone help me
Thanks

**Comment by abrarmalekji345** [comment]
@vickygaugau Done, please update the package to [1.0.6](https://pub.dev/packages/image_collage_widget) Thanks.
