### ISSUE TITLE
Set height of image_collage_widget

### ISSUE THREAD

**Issue by VuThienHung** [Mindinventory/image-collage-widget#15]
Hi team,
How can i set the fix height of image_collage_widget, and items is scale to small to fit the sizebox?
Currently, it is scrolled
Thanks

**Comment by abrarmalekji345** [comment]
Hi @VuThienHung, If you provide height to image_collage_widget it would scale down all the items to fit the given size, it is intentional behaviour. can you please provide your code?

**Comment by mohit-chauhan-mi** [comment]
Closing this issue for now. Please reopen it with more details if needed.
