### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kindaniel** [Mindinventory/image-collage-widget#17]
package is very good, but i cannot downgrade my dependencies to use.

this repo can have a dependencies package updates?

Because image_collage_widget >=1.0.1 depends on image_picker ^0.8.4+4 and my app depends on image_picker ^1.0.7

**Comment by mohit-chauhan-mi** [comment]
@kindaniel We've updated it to the [latest version](https://pub.dev/packages/image_collage_widget). Thanks.
