### ISSUE TITLE
don't support null safety

### ISSUE THREAD

**Issue by ShohidulProgrammer** [Mindinventory/image-collage-widget#6]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:image_collage_widget
 - package:flutter_bloc
 - package:flutter_staggered_grid_view
 - package:plugin_platform_interface
 - package:bloc
 - package:provider
 - package:flutter_file_manager
 - package:image_picker
 - package:permission_handler
 - package:equatable
 - package:image_picker_platform_interface
 - package:rxdart

**Comment by sahilmind** [comment]
@ShohidulProgrammer I apologise for the delayed response,
We have added support for null safety in **image_collage_widget 1.0.3** please have a look.
I am happy to help you if required.
Thanks!
