### ISSUE TITLE
Permission Issue on ios 

### ISSUE THREAD

**Issue by hamadkhan0099** [Mindinventory/image-collage-widget#7]
opening on very first time on ios device it gives this exception, without asking any permission. 
**[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(PERMISSION_DISABLED, Camera data is not available on device, null, null)
#0      Permissions.permissionDisabledMessage (package:image_collage_widget/utils/permissions.dart:83:5)
#1      Permissions._handleInvalidPermissions (package:image_collage_widget/utils/permissions.dart:70:11)
<asynchronous suspension>**

**Comment by sahilmind** [comment]
@hamadkhan0099 I apologise for the delayed response,
handled the permission issue in **image_collage_widget 1.0.3** please have a look.
I am happy to help you if required.
Thanks!
